
FETCH_ALL_TODOS = "FETCH_ALL_TODOS"
DELETE_TODO = "DELETE_TODO"

ADD_NEW_TODO = "ADD_NEW_TODO"
LOGIN_USER = "LOGIN_USER"

FORM_PANEL_UPDATE = "FORM_PANEL_UPDATE"
LOGIN_FORM_UPDATE = "LOGIN_FORM_UPDATE"
