
FETCH_ALL_TODOS = "FETCH_ALL_TODOS"
FETCH_ALL_TODOS_PENDING = "FETCH_ALL_TODOS_PENDING"
FETCH_ALL_TODOS_FULFILLED = "FETCH_ALL_TODOS_FULFILLED"
FETCH_ALL_TODOS_REJECTED = "FETCH_ALL_TODOS_REJECTED"

COMPLETE_TODO = "COMPLETE_TODO"
COMPLETE_TODO_PENDING = "COMPLETE_TODO_PENDING"
COMPLETE_TODO_FULFILLED = "COMPLETE_TODO_FULFILLED"
COMPLETE_TODO_REJECTED = "COMPLETE_TODO_REJECTED"

DELETE_TODO = "DELETE_TODO"
DELETE_TODO_PENDING = "DELETE_TODO_PENDING"
DELETE_TODO_FULFILLED = "DELETE_TODO_FULFILLED"
DELETE_TODO_REJECTED = "DELETE_TODO_REJECTED"

ADD_NEW_TODO = "ADD_NEW_TODO"
ADD_NEW_TODO_PENDING = "ADD_NEW_TODO_PENDING"
ADD_NEW_TODO_FULFILLED = "ADD_NEW_TODO_FULFILLED"
ADD_NEW_TODO_REJECTED = "ADD_NEW_TODO_REJECTED"

LOGIN_USER = "LOGIN_USER"
LOGIN_USER_PENDING = "LOGIN_USER_PENDING"
LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED"
LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED"

FORM_PANEL_UPDATE = "FORM_PANEL_UPDATE"
LOGIN_FORM_UPDATE = "LOGIN_FORM_UPDATE"
