
FETCH_ALL_TODOS = "FETCH_ALL_TODOS"
FETCH_ALL_TODOS_PENDING = "FETCH_ALL_TODOS_PENDING"
FETCH_ALL_TODOS_FULFILLED = "FETCH_ALL_TODOS_FULFILLED"
FETCH_ALL_TODOS_REJECTED = "FETCH_ALL_TODOS_REJECTED"

COMPLETE_TODO = "COMPLETE_TODO"
DELETE_TODO = "DELETE_TODO"
ADD_NEW_TODO = "ADD_NEW_TODO"

LOGIN_USER = "LOGIN_USER"
LOGIN_USER_PENDING = "LOGIN_USER_PENDING"
LOGIN_USER_FULFILLED = "LOGIN_USER_FULFILLED"
LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED"

FORM_PANEL_UPDATE = "FORM_PANEL_UPDATE"
LOGIN_FORM_UPDATE = "LOGIN_FORM_UPDATE"
